name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload Artifacts - OSS version
      uses: actions/upload-artifact@v2
      with:
        name: SkyTube-Oss.apk
        path: app/build/outputs/apk/oss/snapshot/SkyTube-Oss-*.apk
